<?php

namespace AG\LasVegasBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlbumRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlbumRepository extends EntityRepository
{
    public function myFindAll()
    {
        return $this->createQueryBuilder('a')
            ->leftJoin('a.photos', 'p')
            ->addSelect('p')
            ->leftJoin('a.author', 'u')
            ->addSelect('u')
            ->groupBy('a.id')
            ->getQuery()
            ->getResult();
    }
}
