<?php

namespace AG\LasVegasBundle\Entity;

use AG\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PhotoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhotoRepository extends EntityRepository
{
    public function getPhotos($page, $nbPerPage)
    {
        return $this->createQueryBuilder('p')
            ->leftJoin('p.album', 'a')
            ->addSelect('a')
            ->leftJoin('p.author', 'u')
            ->addSelect('u')
            ->orderBy('p.id', 'DESC')
            ->setFirstResult(($page - 1) * $nbPerPage)
            ->setMaxResults($nbPerPage)
            ->getQuery()
            ->getResult();
    }

    public function findMyContributions(User $user)
    {
        return $this->createQueryBuilder('p')
            ->select('COUNT(p.id) nbPhotos, a.id, a.name')
            ->join('p.album', 'a')
            ->where('p.author = :user')
            ->groupBy('a.id')
            ->setParameter('user', $user)
            ->getQuery()
            ->getResult(Query::HYDRATE_ARRAY);
    }
}
