services:
    ag.image_rotator:
        class: AG\LasVegasBundle\Services\ImageRotator

    ag.thumbnail_handler:
        class: AG\LasVegasBundle\DoctrineListener\ThumbnailHandler
        arguments: [@liip_imagine.cache.manager]
        tags:
            - { name: doctrine.event_listener, event: postRemove }
